app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime
from sqlalchemy import func

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    pitches = db.relationship("Pitch", backref="user", lazy="dynamic")
    Comments = db.relationship("Comments", backref="user", lazy="dynamic")
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_secure = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_secure, password)

    def __repr__(self):
        return f'User {self.username}'

class Pitch(db.Model):
    """
    This is the class which we will use to create the pitches for the app
    """
    __tablename__ = "pitches"

    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    category = db.Column(db.String)
    Comments = db.relationship("Comments", backref="pitch", lazy="dynamic")

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    def get_pitch_comments(self):
        pitch = Pitch.query.filter_by(id=self.id).first()
        comments = Comments.query.filter_by(pitch_id=pitch.id).order_by(Comments.time.desc())
        return comments

class Comments(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    pitch_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit() 

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, SelectField
from wtforms.validators import Required

class DisplayPitch(FlaskForm):
    text = TextAreaField('Type in your pitch', validators=[Required()])
    categories = SelectField('Select your preffered category', choices=[('HUMOR', 'HUMOR'), ('BUSINESS', 'BUSINESS'), ('INSPIRATIONAL', 'INSPIRATIONAL'), ('SPIRITUAL', 'SPIRITUAL')])
    submit = SubmitField('post')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators=[Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    comment = TextAreaField('Add a comment.', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import config_options
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

mail = Mail()

simple = SimpleMDE()

photos = UploadSet('photos', IMAGES)
def create_app(config_name):

    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # Will add the views and forms

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # configure UploadSet
    configure_uploads(app,photos)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    mail.init_app(app)

    simple.init_app(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views, errors

app/main/views.py
from ..models import User, Comments, Pitch
from . import main
from flask import render_template, request, redirect, url_for, abort
from .forms import UpdateProfile, DisplayPitch, CommentForm
from flask_login import login_required, current_user
from .. import db, photos

@main.route("/", methods=['GET', 'POST'])
def index():
    form = DisplayPitch()
    if form.validate_on_submit():
        category = form.categories.data
        pitch = form.text.data

        # Updated post
        new_pitch = Pitch(category=category, content=pitch, user=current_user)

        # save pitch method
        new_pitch.save_pitch()
     
    pitches = Pitch.query.all()
    title = "Home"
    return render_template('index.html', title=title, pitch_form=form, pitches=pitches)  

@main.route('/pitch/<int:id>', methods=['GET', 'POST'])
@login_required
def new_comment(id):
    pitch = Pitch.query.filter_by(id=id).first()
    form = CommentForm()
    comment = Comments.query.filter_by(pitch_id=id).all()

    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comments(comment=comment, user_id=current_user.id, pitch=pitch)
        new_comment.save_comment()
        return redirect(url_for('main.new_comment', id=pitch.id))

    title = "COMMENTS"   
    return render_template('comments.html', comment=comment, comment_form=form, title=title, pitch=pitch)    
    
@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username=uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile_page.html", user=user)

@main.route('/user/<uname>/update', methods=['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname=user.username))

    return render_template('profile/update.html', form=form)

@main.route('/user/<uname>/update/pic', methods=['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username=uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  -->
{% block navbar %}
{% include 'navbar.html' %}
{%block styles %}
{{super()}}
<link href="https://fonts.googleapis.com/css?family=Cute+Font|Indie+Flower|Kanit|Raleway|Righteous|ZCOOL+KuaiLe&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Orbitron&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Architects+Daughter&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Faster+One&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Irish+Grover&display=swap" rel="stylesheet">
{{ simplemde.css}}
{{ simplemde.js }}
{% endblock %}
{%endblock%}

app/templates/comments.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<h2 style="text-align: center;"><strong><u>COMMENTS.</u></strong></h2><br><br>
<div class="container">
  <div class="row">
    {% for comment in comment %}
    <div class="col-md-4" style="padding-bottom: 2.5%; text-align: center;">
      <ul>
        <li>
          <h3 style="font-family: 'Architects Daughter', cursive; font-size:210%">{{comment.comment}}</h3>
        </li>
      </ul>
    </div>
    {% endfor %}
  </div>
  <br<br>
    {% if current_user.is_authenticated %}
    {{wtf.quick_form(comment_form)}}
    {% else %}
    {% endif %}
</div>
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
<h1>WHOOOPS we can't find that page</h1>
<div class="btn btn-primary">
  <a href="/">HOME</a>
</div>
{% endblock %}

app/templates/index.html
<body>
  {% extends 'base.html'%}
  {% import 'bootstrap/wtf.html' as wtf%}

  <meta charset="utf-8">
  {% if title %}
  <title> {{ title }}</title>
  {% else %}
  <title> Pitch </title>
  {% endif %}
  {% block content %}

  <div class="container">
    <h2 style="text-align: center;"><strong><u>WELCOME TO PITCHES.💚</u></strong></h2><br><br>
    <div class="row" style="margin-bottom: 0%;">
      {% if current_user.is_authenticated %}
      {% for pitch in pitches %}
      <div class="col-md-4 col-xs-4 col-lg-4 col-sm-4" style=" padding-bottom: 2.5%; text-align: center;">
        <h2 class="card-text" style="font-family: 'Orbitron', sans-serif;">{{pitch.content}}</h2>
        <h5 class="card-text">Category:{{pitch.category}}</h5>
        <a href="/pitch/{{pitch.id}}">comments</a>
      </div>
      {% endfor %}
    </div>
    <br><br>
    {{wtf.quick_form(pitch_form)}}
    {%else%}
    <h2
      style="font-size: 50px; text-align: center; font-family: 'Faster One', cursive;">
      TO VIEW AND COMMENT ON PITCHES, PLEASE LOG IN IF YOU ALREADY HAVE AN ACCOUNT AND IF NOT, PLEASE SIGN UP.</h2>
    <br><br>
    <h1 style="text-align: center; font-size: 85px;">👍🏿</h1>
    {%endif%}
  </div>
  {% endblock %}
</body>

app/templates/navbar.html
  <div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"> PITCHES </a>
      </div>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li style="color:white;"><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <li><a href="{{url_for('auth.login')}}">Log in</a></li>
        {%endif%}
      </ul>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="/">Home</a></li>
      </div>

    </div>
  </div>

app/templates/profile/profile_page.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
  <div class="row">
    <!-- displaying  Username-->
    <div class="col-md-6">
      <h3> {{user.username| capitalize}} </h3>

      <!--Displaying user bio-->
      {% if user.bio %}
      <h3 style="font-family: 'Irish Grover', cursive;"> {{user.bio}}</h3>
      {%else%}
      <h3 style="font-family: 'Irish Grover', cursive;"> {{user.username| capitalize}} has no bio </h3>
      {% endif %}
      {% if user == current_user %}
      <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
      {% endif %}
    </div>

    <!--Display profile photo-->
    <div class="col-md-6">
      {% if user.profile_pic_path %}
      <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
      {%else%}
      <p>No profile picture</p>
      {% endif %}
    </div>
    <br><br>

    {% if user == current_user %}
    <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">
      <input type="file" name="photo" class="form-control" required>
      <input type="submit">
    </form>
    {% endif %}
  </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}